### ISSUE TITLE
Limit which projects are shown

### ISSUE THREAD

**Issue by epernst** [tfenster/azdevops-vscode-simplify#10]
It would be great if I could filter which projects were shown within my organization. 
Right now, I see a list of 50+ projects, but I only have open work items in one. So, it would be great if this could be filtered to show only projects with active work items.

(This was also suggested by Marcus Nordlund on Twitter).

**Comment by tfenster** [comment]
As I answered on Twitter, I don't think we can do this in a performant way. But we should be able to allow you to easily set up a whitelist of projects that you want to see

**Comment by epernst** [comment]
A whitelist would be fine, especially if the setting is part of the repo.

**Comment by DavidFeldhoff** [comment]
I think I would implement the setting like this.
"projectsToShow": [
  "[organization1]/project3",
  "[organization1]/project4",
  "[organization2]/project1",
]
 what do you think about it? Any shortcomings?

**Comment by tfenster** [comment]
Purely from a "I have seen similar problems" standpoint, but no real clue whether that applies here as well:

- Allow wildcards. E.g. I have `"<customer x> customizations"`, `"<customer y> customizations"` and `"<customer z> customizations"`, then it might be good to do `"* customizations"` as filter
- Add a right-click option on the tree to add a project to the list without manually changing the setting
- Also implement `"projectsToHide"` in the same way (interesting question is what happens if a project is in both)
- Do the same on org level

Just ideas, feel free to ignore all of them :)

**Comment by DavidFeldhoff** [comment]
Great ideas!

**Comment by tfenster** [comment]
I get this in azdevops-api.ts trying to run your branch

![image](https://user-images.githubusercontent.com/15346084/208859697-423c8f8f-476a-448b-b869-8188a89e59df.png)

Did you maybe make a local change that isn't committed/pushed yet?
