### ISSUE TITLE
Azure DevOps Server possibility

### ISSUE THREAD

**Issue by CarstenMertes** [tfenster/azdevops-vscode-simplify#12]
Hi, 
will it be possible to use it with Azure DevOps Server on-prem?

**Comment by tfenster** [comment]
Technically, it should be possible. We would need a configuration setting for the URL of your Azure DevOps Server and then call that instead of the SaaS URL. That being said, I don't have access to an on-prem server anymore, so I wouldn't be able to do any testing and therefore can't implement it. But feel free to create a PR, if you want to support it!

@DavidFeldhoff do you agree?

**Comment by DavidFeldhoff** [comment]
I don't have access to an on-prem Server as well. (never had). So therefore I've no clue what has to be done for this, but your approach seems at least comprehensible :)

**Comment by tfenster** [comment]
@CarstenMertes, unfortunately neither @DavidFeldhoff nor I would be able to solve this, so I'll close this without a solution. But if you would ever create a PR to fix this, we would be more than happy to take a look
