### ISSUE TITLE
Expanding a second project gives an error

### ISSUE THREAD

**Issue by AskeHolst** [tfenster/azdevops-vscode-simplify#3]
I have access to multiple orgs with multiple projects. Opening one project works fine, the second fails with an error.
It does not matter which project I open first. Also it does not have to projects in two different orgs.

![image](https://user-images.githubusercontent.com/8398485/202871933-b764f1c8-6810-44fe-9faa-0f4f2b7b61f8.png)

![image](https://user-images.githubusercontent.com/8398485/202871945-0c8affbc-fec3-448e-abac-2702e9cdf667.png)

**Comment by DavidFeldhoff** [comment]
Hi Aske, I've just fixed it. Thanks for creating this one already at the weekend, so we were able to fix it before the first working day :) Looking forward for your confirmation and closing of the issue afterwards.

**Comment by AskeHolst** [comment]
I get a new error. I even tried uninstalling and reinstalling 0.0.2, maybe there is something cached.
![image](https://user-images.githubusercontent.com/8398485/202874134-490a10d9-d86a-4c61-b8d6-8f054f7db46b.png)

**Comment by DavidFeldhoff** [comment]
Hm, that's really a new one. For me it was working now. Give me a bit to troubleshoot more

**Comment by DavidFeldhoff** [comment]
the error regarding `Cannot read properties of undefined (reading 'value')` is a consequence of the other error.
What we're doing is that we try to load the organizations at this point.

Are there any infos under Output -> Log (Window)?
![image](https://user-images.githubusercontent.com/53570297/202877440-81f3971d-633a-44d4-9a69-b1a5f15d74de.png)

Do you have any idea why the http request might fail? Has something failed with the login, so that the credentials are not valid or something like that? I'm talking about this login: 
![image](https://user-images.githubusercontent.com/53570297/202877541-01cd08c7-1c90-44cd-8b2f-f9dbcfda27c1.png)
Maybe it might also be worth a try to execute `Azure: Sign out` once. Stepping a bit in the dark :)

**Comment by tfenster** [comment]
@AskeHolst This is what it should look like if you are not logged in

![sign in](https://user-images.githubusercontent.com/15346084/202895069-db9283c3-9e3a-473c-9069-8f4a3e3c6aef.gif)

Does that happen for you? I tried to improve the behavior with #5, lets see if @DavidFeldhoff agrees

**Comment by AskeHolst** [comment]
There is an error in Log (Windows), see below, but signing out and in again resolved it. 
 
![image](https://user-images.githubusercontent.com/8398485/202899913-14a1b306-eee3-4923-8548-a3f03d6d2c5a.png)

**Comment by DavidFeldhoff** [comment]
Okay, so you're now able to use the extension without any further issues after signing out an in again?

**Comment by AskeHolst** [comment]
Yes, after signing out and in again, it works without error. 
I have just never had the need to sign out and sign in again in the four years I have worked in VSCode, so it was not obvious to me.
