### ISSUE TITLE
[Feature Request] Ctrl+F : Search on work item id?

### ISSUE THREAD

**Issue by fvet** [tfenster/azdevops-vscode-simplify#34]
When using Ctrl+F in the Simplify list, you can search / filter list entries based on the work item **description**. 

![image](https://user-images.githubusercontent.com/25268332/212086502-c24800c8-eb6e-4629-97ff-9caa4b310408.png)

Is it doable to also search on work item **id** instead? Might come in handy if you already had the id and just could search on it.

![image](https://user-images.githubusercontent.com/25268332/212086252-0562798c-b442-4e62-ac22-db65beff6691.png)

**Comment by tfenster** [comment]
@fvet Good suggestion. I have to admit that I don't know how the Ctrl+F search can be influenced, but will try to figure it out. @DavidFeldhoff do you know?

If anyone comes across this and knows, please comment

**Comment by DavidFeldhoff** [comment]
Don't know as well if it's possible. I can take a look, but no promises. And searching using the ID is possible using the command that we have. 

Is there functionality missing with that command or would you just like to have a second way to achieve the same?

**Comment by DavidFeldhoff** [comment]
I had a short look into it and can't find anything how to extend the search until now. Only solution that would come to my mind would be to not show the workitem id in the less prominent `description`, but instead append it to the `label` property, then it would be searchable as well. Would that be an approach?

**Comment by fvet** [comment]
No need to fix if it's not supported out of the box. It was more like a question instead of a feature request ;)

Can you still elaborate a bit the below?

_And searching using the ID is possible using the command that we have._

**Comment by DavidFeldhoff** [comment]
With that I was referring to the `Add work item to commit message` command. So it's only of help for you if you actually want to add it to the commit message. The other actions you're able to do in the view like `Create branch for this` or `Open in Browser` are not supported there. And for now we have nothing planned there.
![image](https://user-images.githubusercontent.com/53570297/215054406-52402fc4-4f32-4c66-b005-2a3bc2437547.png)
![image](https://user-images.githubusercontent.com/53570297/215054413-4ea405f1-3c57-4079-8906-4fd53354f40c.png)

But giving it a second thought that was probably not your use case, right? Because if you know the work item id, then you would've been able to add it to the commit message directly anyway..

**Comment by DavidFeldhoff** [comment]
@fvet I think this one can be closed, right?
