### ISSUE TITLE
404 error after creating new branch

### ISSUE THREAD

**Issue by fvet** [tfenster/azdevops-vscode-simplify#9]
When i click the 'create branch' option and fill a branch name, a local branch is created with the entered name. Afterwards, I'm getting a 404 error.

Any hints?

![image](https://user-images.githubusercontent.com/25268332/202921142-c48225d8-1945-4183-aa96-bc0793253a35.png)

**Comment by fvet** [comment]
Might possibly be related to a branch name that was already used (which would be nice it that would be supported. It would allow switching between work items / branches).

_2022-11-20 20:11:45.841 [error] {"message":"Failed to execute git","stdout":"","stderr":"fatal: a branch named '2' already exists\n","exitCode":128,"gitCommand":"checkout","gitArgs":["checkout","-q","-b","2","--no-track"]}_

**Comment by DavidFeldhoff** [comment]
Sounds logical. I've a solution in mind for this. We could retrieve the remote branch names first and then if you're entering the new branch name directly validating if the branch name is unique, otherwise you won't be able to submit that non-unique branch name. Would that be a valid solution for you as well?

**Comment by tfenster** [comment]
@fvet this should be fixed with the next release. Please let us know after testing if this doesn't fit your needs
